<template>
<section class="loader" v-if="loader == true">
  <div class="loader-content">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; display: block; shape-rendering: auto;" width="121px" height="121px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<g transform="translate(26.5,26.5)">
  <rect x="-20.5" y="-20.5" width="41" height="41" fill="#67c23a">
    <animateTransform attributeName="transform" type="scale" repeatCount="indefinite" dur="0.6578947368421053s" keyTimes="0;1" values="1.1500000000000001;1" begin="-0.19736842105263158s"></animateTransform>
  </rect>
</g>
<g transform="translate(73.5,26.5)">
  <rect x="-20.5" y="-20.5" width="41" height="41" fill="#549c30">
    <animateTransform attributeName="transform" type="scale" repeatCount="indefinite" dur="0.6578947368421053s" keyTimes="0;1" values="1.1500000000000001;1" begin="-0.13157894736842105s"></animateTransform>
  </rect>
</g>
<g transform="translate(26.5,73.5)">
  <rect x="-20.5" y="-20.5" width="41" height="41" fill="#549c30">
    <animateTransform attributeName="transform" type="scale" repeatCount="indefinite" dur="0.6578947368421053s" keyTimes="0;1" values="1.1500000000000001;1" begin="0s"></animateTransform>
  </rect>
</g>
<g transform="translate(73.5,73.5)">
  <rect x="-20.5" y="-20.5" width="41" height="41" fill="#67c23a">
    <animateTransform attributeName="transform" type="scale" repeatCount="indefinite" dur="0.6578947368421053s" keyTimes="0;1" values="1.1500000000000001;1" begin="-0.06578947368421052s"></animateTransform>
  </rect>
</g>
<!-- [ldio] generated by https://loading.io/ --></svg>

  </div>
  
</section>
  <Header/>
  <Main/>
  <Specs/>
  <Managment/>
  <Customer/>
  <Collaborative/>
  <Quick/>
  <Strategies/>
  <Price/>
  <Clients/>
  <Banner/>
  <Footer/>
</template>

<script>
import Header from '@/components/Header.vue'
import Main from '@/components/Main.vue'
import Specs from '@/components/Specs.vue'
import Managment from '@/components/Managment.vue'
import Customer from '@/components/Customer.vue'
import Collaborative from '@/components/Collaborative.vue'
import Quick from '@/components/Quick.vue'
import Strategies from '@/components/Strategies.vue'
import Price from '@/components/Price.vue'
import Clients from '@/components/Clients.vue'
import Banner from '@/components/Banner.vue'
import Footer from '@/components/Footer.vue'

export default {
  components:{
Header, Main, Specs, Managment, Customer, Collaborative, Quick, Strategies, Price, Clients, Banner, Footer
  },
  data(){
    return{
      loader: true
    }
  },
  mounted(){
    this.loader = false
  }
}
</script>

<style lang="scss">
@import './colors.scss';
@import url(https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic);
*{
  font-family: 'Roboto', sans-serif;
}
html,body, p,ul,ol,li, h1, h2, span{
  margin: 0;
  padding: 0;
}
::-webkit-scrollbar {
  width: 0;
}
.loader{
  position: fixed;
  width: 100%;
  height: 100%;
  background-color: $white;
  z-index: 1000;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

</style>
